get:
  tags:
    - Products
  summary: Get products (paged and filtered if requested)
  description: Return a list of all products, paged and filtered (if requested).
  operationId: getProducts
  parameters:
    - name: page
      in: query
      required: false
      description: page to be shown
      schema:
        type: integer
        default: 0
        minimum: 0
    - name: size
      in: query
      required: false
      description: page size
      schema:
        type: integer
        default: 20
        maximum: 30 # TODO: agree with the team the reasonable max page size
    - name: title
      in: query
      required: false
      description: search string in title
      schema:
        type: string
        example: "jeans"
        minLength: 3 # TODO: agree with the team the reasonable min search string size
        maxLength: 50 # TODO: agree with the team the reasonable max search string size
    - name: orderByPrice
      in: query
      required: false
      description: order result by price (lowest first - asc, highest first - desc)
      schema:
        type: string
        example: "asc"
        pattern: '^(asc|desc)$'
    - name: maxPrice
      in: query
      required: false
      description: filter up to max price indicated
      schema:
        type: integer
        example: 640
        minimum: 0
    - name: category
      in: query
      required: false
      description: a list of categories
      schema:
        type: array
        maxItems: 10 # TODO: agree with the team the reasonable categories list size
        items:
          type: string
          example: activewear


  responses:
    '200':
      description: List of products by page and filtered (if any)
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/ProductPageResponse.yaml'
    '400':
      description: Invalid query parameters
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/ErrorResponse.yaml'
    '500':
      description: Internal error.
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/ErrorResponse.yaml'

