CREATE TABLE model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    description TEXT,
    image_url TEXT,
    price DECIMAL
);

CREATE TABLE product (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name VARCHAR(100),
     size VARCHAR(5),
     color VARCHAR(50),
     stock INT,
     active BOOLEAN,
     model_id BIGINT,

     CONSTRAINT fk_model FOREIGN KEY (model_id) REFERENCES model(id)
);

CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50)
);

CREATE TABLE model_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT,
    model_id BIGINT,

    CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES category(id),
    CONSTRAINT fk_model FOREIGN KEY (model_id) REFERENCES model(id)
);

CREATE TABLE cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE,
    created_at DATE,
    totalPrice DECIMAL
);

CREATE TABLE cart_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity INT,
    cart_id BIGINT,
    product_id BIGINT,
    unitPrice DECIMAL,
    totalPrice DECIMAL,

    CONSTRAINT fk_cart FOREIGN KEY (cart_id) REFERENCES cart(id),
    CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE,
    special_instructions TEXT,
    totalPrice DECIMAL,
    created_at DATE
);

CREATE TABLE order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT,
    product_id BIGINT,
    unitPrice DECIMAL,
    totalPrice DECIMAL,
    quantity INT,

    CONSTRAINT fk_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES product(id)
)