CREATE TABLE IF NOT EXISTS product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) ,
    description TEXT,
    image_url TEXT,
    price DECIMAL,
    active BOOLEAN
);

CREATE TABLE IF NOT EXISTS product_variant (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name VARCHAR(100),
     size VARCHAR(5),
     color VARCHAR(50),
     stock INT,
     active BOOLEAN,
     product_id BIGINT,

     CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE IF NOT EXISTS category (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS product_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id SMALLINT,
    product_id BIGINT,

    CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES category(id),
    CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES product(id),
    CONSTRAINT product_category_unique UNIQUE (category_id, product_id)
);

CREATE TABLE IF NOT EXISTS cart (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_price DECIMAL
);

CREATE TABLE IF NOT EXISTS cart_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity INT NOT NULL,
    cart_id BIGINT NOT NULL,
    product_variant_id BIGINT NOT NULL,
    unit_price DECIMAL,
    total_price DECIMAL,

    CONSTRAINT fk_cart FOREIGN KEY (cart_id) REFERENCES cart(id) ON DELETE CASCADE,
    CONSTRAINT fk_product_variant FOREIGN KEY (product_variant_id) REFERENCES product_variant(id),
    CONSTRAINT cart_product_unique UNIQUE (cart_id, product_variant_id)
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    special_instructions TEXT,
    total_price DECIMAL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_variant_id BIGINT NOT NULL,
    unit_price DECIMAL,
    total_price DECIMAL,
    quantity INT NOT NULL,

    CONSTRAINT fk_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_product_variant FOREIGN KEY (product_variant_id) REFERENCES product_variant(id),
    CONSTRAINT  order_product_unique UNIQUE (order_id, product_variant_id)
)