openapi: 3.0.3
info:
  title: Modu API
  description: API for Modu e-commerce
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: local server

tags:
  - name: Products
    description: read operations to get products
  - name: Product Variants
    description: read operations to get product variants
  - name: Categories
    description: read operation to get categories
  - name: Cart
    description: operations related to cart handling (add item, modify quantity, validate)
paths:
  /products:
    $ref: './paths/products/products.yaml'
  /product/{productId}:
    $ref: './paths/products/get-product-by-id.yaml'
  /products/{productId}/product_variants:
    $ref: './paths/products/get-variants-by-product-id.yaml'
  /categories:
    $ref: './paths/categories.yaml'
  /cart/addItem:
    $ref: './paths/cart/add-item.yaml'
  /cart/updateItem/{itemId}:
    $ref: './paths/cart/update-item.yaml'

components:
  schemas:
    ProductResponse:
      $ref: './components/schemas/ProductPageResponse.yaml'