openapi: 3.0.3
info:
  title: Modu API
  description: API for Modu e-commerce
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: local server

tags:
  - name: Products
    description: read operations to get products
  - name: Categories
    description: read operation to get categories
  - name: Cart
    description: operations related to cart handling (add item, modify quantity, validate)
paths:
  /models:
    $ref: './paths/products/models.yaml'
  /model/{modelId}:
    $ref: './paths/products/get-product-by-id.yaml'
  /categories:
    $ref: './paths/categories.yaml'
  /cart/addItem:
    $ref: './paths/cart/addItem.yaml'

components:
  schemas:
    ProductResponse:
      $ref: './components/schemas/ProductsResponse.yaml'