type: object
required:
  - product_id
  - url
properties:
  product_id:
    type: integer
    format: int64
    example: 1
  url:
    type: string
    example: https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&w=800&q=80